### PR TITLE
Fix: fallbacks on other score computation when an entry is too old

### PR DESCRIPTION
**Pull request by guillaumearm**
Hi,

I have an issue when 2 timestamps overlap the 14 days limit.

- I added 2 tests which confirm my issue.
- I added 2 lines of code to avoid early return when computed score is equals to zero.

Is that enough comprehensible ?
Do you need more infos or tests ?

### CODE REVIEW

**Comment by wearhere** [comment]
Thanks for the PR @guillaumearm. Without me (or future readers) having to run the tests, what would frecency do prior to these changes? (Can you describe the issue that you are correcting?)

**Comment by guillaumearm** [comment]
@wearhere: sure.

## Case 1 - fallbacks on sub-query match
- I search for `br` and I select `brad neuberg`
- 13 days later, I search for `brad` and I select `brad neuberg` too
- 2 days laters, I search for `br`
- At this point the expected first result should be `brad neuberg` but it's not

This is due to this early return: https://github.com/mixmaxhq/frecency/pull/11/files#diff-1fdf421c05c1140f6d71444ea2b27638L297

Because there is 15 days I didn't looking for `br`, the computed score for exact-query match is zero and the algorithm didn't try subQuery match.

The idea here is to return only if score is `> 0`
If not, frecency will try sub-query match and in my case, a search for `brad` will bring `brad neuberg` at first result.

## Case 2 - fallbacks on recent selections match
Same problem here but between `sub-query match` and `recent selections match`.
https://github.com/mixmaxhq/frecency/pull/11/files#diff-1fdf421c05c1140f6d71444ea2b27638L316

- I search for `brad` and I select `brad neuberg`
- 13 days later, I search for `bra` and I select `brad neuberg` too
- 2 days later I search for `brad`
- At this point, the expected first result should be `brad neuberg` but it's not

-----------

1. When I search for `brad`, exact-query match will return a zero score (`brad` was searched 15 days ago), so it fallbacks on sub-query match.
2. `brad` is not a sub-query for `bra`, sub-query match will return a zero score, so it fallbacks on recent selections matchs
3. `bra` is a recent selection and his score will be bumped

**Comment by wearhere** [comment]
cool thanks @guillaumearm !

**Comment by wearhere** [comment]
Published as frecency@1.3.1

**Pull request merged**
